name: BumpBlaster
channels:
  - numba
  - defaults
  - anaconda
  - conda-forge
dependencies:
  # - pip
  - numpy
  - scipy
  - pyqt
  - pyserial
  - pyqtgraph
  - ipython
  - pandas
  - pywin32
  - python=3.6
  - numba
  - pillow
  - pip:
    - -e .

# in addition, have to install pycapture2 api